config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products
  resources :sub_category_types
  resources :sub_categories
  resources :categories
  resources :homes
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/sub_category_types_controller.rb
class SubCategoryTypesController < ApplicationController
  before_action :set_sub_category_type, only: [:show, :edit, :update, :destroy]

  # GET /sub_category_types
  # GET /sub_category_types.json
  def index
    @sub_category_types = SubCategoryType.all
  end

  # GET /sub_category_types/1
  # GET /sub_category_types/1.json
  def show
  end

  # GET /sub_category_types/new
  def new
    @sub_category_type = SubCategoryType.new
  end

  # GET /sub_category_types/1/edit
  def edit
  end

  # POST /sub_category_types
  # POST /sub_category_types.json
  def create
    @sub_category_type = SubCategoryType.new(sub_category_type_params)

    respond_to do |format|
      if @sub_category_type.save
        format.html { redirect_to @sub_category_type, notice: 'Sub category type was successfully created.' }
        format.json { render :show, status: :created, location: @sub_category_type }
      else
        format.html { render :new }
        format.json { render json: @sub_category_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_category_types/1
  # PATCH/PUT /sub_category_types/1.json
  def update
    respond_to do |format|
      if @sub_category_type.update(sub_category_type_params)
        format.html { redirect_to @sub_category_type, notice: 'Sub category type was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_category_type }
      else
        format.html { render :edit }
        format.json { render json: @sub_category_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_category_types/1
  # DELETE /sub_category_types/1.json
  def destroy
    @sub_category_type.destroy
    respond_to do |format|
      format.html { redirect_to sub_category_types_url, notice: 'Sub category type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category_type
      @sub_category_type = SubCategoryType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_type_params
      params.require(:sub_category_type).permit(:name, :sub_category_id)
    end
end

app/helpers/sub_category_types_helper.rb
module SubCategoryTypesHelper
end

app/views/sub_category_types/_form.html.erb
<%= form_with(model: sub_category_type, local: true) do |form| %>
  <% if sub_category_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_category_type.errors.count, "error") %> prohibited this sub_category_type from being saved:</h2>

      <ul>
      <% sub_category_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :sub_category_id %>
    <%= form.number_field :sub_category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_category_types/edit.html.erb
<h1>Editing Sub Category Type</h1>

<%= render 'form', sub_category_type: @sub_category_type %>

<%= link_to 'Show', @sub_category_type %> |
<%= link_to 'Back', sub_category_types_path %>

app/views/sub_category_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Category Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sub category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_category_types.each do |sub_category_type| %>
      <tr>
        <td><%= sub_category_type.name %></td>
        <td><%= sub_category_type.sub_category_id %></td>
        <td><%= link_to 'Show', sub_category_type %></td>
        <td><%= link_to 'Edit', edit_sub_category_type_path(sub_category_type) %></td>
        <td><%= link_to 'Destroy', sub_category_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Category Type', new_sub_category_type_path %>

app/views/sub_category_types/new.html.erb
<h1>New Sub Category Type</h1>

<%= render 'form', sub_category_type: @sub_category_type %>

<%= link_to 'Back', sub_category_types_path %>

app/views/sub_category_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sub_category_type.name %>
</p>

<p>
  <strong>Sub category:</strong>
  <%= @sub_category_type.sub_category_id %>
</p>

<%= link_to 'Edit', edit_sub_category_type_path(@sub_category_type) %> |
<%= link_to 'Back', sub_category_types_path %>